### ISSUE TITLE
Insert law not being generated by QuickSpec v2

### ISSUE THREAD

**Issue by rudymatela** [nick8325/quickspec#10]
Hello Nick,

This is a follow-up from what we tried last Friday.

### Simple example

The following example signature containing just `insert`:

    {-# LANGUAGE ScopedTypeVariables, ConstraintKinds, RankNTypes, ConstraintKinds, FlexibleContexts #-}
    import QuickSpec
    import Data.List

    sig =
      signature {
        maxTermSize = Just 9,
        maxTests = Just 10000,
        constants = [
          constant "insert" (Data.List.insert :: Int -> [Int] -> [Int]) ]}

    -- This should generate:
    -- insert x (insert y xs) == insert y (insert x xs)
    main = quickSpec sig

Should generate the following law:

    insert x (insert y xs) == insert y (insert x xs)

Note that inserting elements does commute:

    > quickCheck (\x y xs -> insert (x::Int) (insert y xs) == insert y (insert x xs))
    +++ OK, passed 100 tests.

### More elaborate example

A more elaborate example, that generates the above law in some unexpected form, is shown below.  It is a slightly modified version of the example we wrote together on Friday.

    {-# LANGUAGE ScopedTypeVariables, ConstraintKinds, RankNTypes, ConstraintKinds, FlexibleContexts #-}
    import QuickSpec
    import Data.List

    sorted :: Ord a => [a] -> Bool
    sorted [] = True
    sorted [x] = True
    sorted (x:y:xs) = x <= y && sorted (y:xs)

    -- With |==> on the background,
    -- an equation:
    -- (precond |==> x) == (precond |==> y)
    --
    -- means:
    -- precond ==> (x == y)
    (|==>) :: Bool -> a -> a
    True  |==> x = x
    False |==> x = undefined

    bg =
      signature {
        maxTermSize = Just 9,
        maxTests = Just 10000,
        constants = [
          constant "|==>" ((|==>) :: Bool -> A -> A),
          constant "True" True,
          constant "&&"  (&&) ]}

    sig =
      signature {
        maxTermSize = Just 9,
        maxTests = Just 10000,
        constants = [
          constant "sorted" (sorted :: [Int] -> Bool),
          constant "insert" (Data.List.insert :: Int -> [Int] -> [Int]),
          constant "sort" (sort :: [Int] -> [Int]) ]}

    -- We wanted it to generate:
    -- sorted xs  ==>  sorted (insert x xs)
    --
    -- encoded as:
    -- sorted xs |==> sorted (insert x xs) == True
    main = quickSpecWithBackground bg sig

This generates the strange law:

    sorted (sort js) |==> insert j (insert i is) = insert i (insert j is)

It sounds strange, as it should be true independently of the precondition on the left side.

I'll try to find why when I get the time: if it is a bug or something that I (we) are not understanding correctly.

**Comment by nick8325** [comment]
This seems to be working now! I fixed a few bugs with the test data generation in the meantime.
