### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by c-cube** [nick8325/quickspec#12]
I cannot build quickspec with cabal (I don't know much about cabal though) because it tries to install `jukebox` even when I try to disable it. I have ghc 8.0.1 on archlinux. It would be nice, alternatively, to have some instructions about the build in the readme.

I tried:

```
cabal configure --flags='-jukebox -z3'
cabal install
```

**Comment by nick8325** [comment]
What error do you get? It works for me (also GHC 8.0.1 on Arch). I just used `cabal update && cabal install`.

Could you attach the output of `cabal install -v2`?

**Comment by c-cube** [comment]
Now it builds, it's weird. Sorry for the disturbance.
