### ISSUE TITLE
Strange conditional laws

### ISSUE THREAD

**Issue by rudymatela** [nick8325/quickspec#16]
Hello @nick8325 and @MaximilianAlgehed,

I _think_ I have found a bug in the generation of conditional equations.
(or it may be just me using QuickSpec wrongly)

Consider the following example quickspecing program about `(:)` and `insert`:

    import QuickSpec hiding (insert)
    import Data.List (insert)

    main = quickSpec signature
      { maxTermSize = Just 9
      , constants =
          [ constant ":"  ((:) :: Int -> [Int] -> [Int])
          , constant "insert" (insert :: Int -> [Int] -> [Int])
          ]
      , predicates =
          [ predicate "<=" ((<=) :: Int -> Int -> Bool)
          ]
      }

Running it yields the following nice law describing one case of `insert`:

    5. x <= y => insert x (y : xs) = x : (y : xs)

So far so good.

### Missing law?

However, I would expect the following recursive case of `insert` to appear (but it does not):

    ?. y <= x => insert x (y : xs) = (y : insert x xs)

It has the correct size, I presume.

### Strange laws.

To try to make QuickSpec print that law,  I have added the following predicate:

    , predicate "<"  ((<)  :: Int -> Int -> Bool)

With that, I get some strange laws:

    5. y < x2 & z <= y2 => y < z = x < x
    8. y < z & x <= x2 => insert x (y : xs) = x : (y : xs)

With no sign of the recursive case of `insert`.

Is this a bug, or am I using the `predicates` feature wrong?

### Using a generator

If I change the suffix of the above program to:

    ...
      , predicates =
          [ predicateGen "<=" ((<=) :: Int -> Int -> Bool) leGen
          , predicateGen "<"  ((<)  :: Int -> Int -> Bool) ltGen
          ]
      }
  
    leGen :: Gen [Dynamic]
    leGen = do
      x1 <- (arbitrary :: Gen Int)
      x2 <- (arbitrary :: Gen Int)
      return [toDyn $ x1, toDyn $ x1 + x2]

    ltGen :: Gen [Dynamic]
    ltGen = do
      x1 <- (arbitrary :: Gen Int)
      x2 <- (arbitrary :: Gen Int)
      return [toDyn $ x1, toDyn $ x1 + x2 + 1]

like in `examples/Conditionals.hs`, all conditional laws involving `insert` disappear (including the correct one):

      1. x < z & x2 <= y => x = y        
      2. x <= x = True                   
      3. x < x = y < y                   
      4. insert x (x : xs) = x : (x : xs)
      5. insert y (insert x xs) = insert x (insert y xs)

### Further information.

I tried with `maxTests = Just 10000` and I still get the same result.

This happens on both @nick8325 and @MaximilianAlgehed branches  (specifically: 9612ec5 and MaximilianAlgehed/quickspec@c5c8244).

Is there a bug, or am I doing something wrong?  (In case it is really a bug: I am aware the conditionals feature is being worked on at the moment and that you guys may be already aware of this issue.  But I thought it would be nice for you guys to know.)

Kind Regards,
Rudy

### P.S.

I tagged @MaximilianAlgehed because he seems to be the one in charge of the (indeed very cool) predicates feature.  I was unsure whether to submit this issue on here or on his clone, ended-up submitting here.

**Comment by MaximilianAlgehed** [comment]
Hrm, I will have to look in to this in some more detail before I can give an account of what is going on.
What happens if you try this on: https://github.com/MaximilianAlgehed/quickspec/commit/fd53aae3acdcba0e962a72bce652f102c13aaeb9 ?

**Comment by rudymatela** [comment]
Hooray!  It works!

To compile, I had to change predicates to:

      , predicates =
          [ predicate (undefined :: Proxy "<=") ((<=) :: Int -> Int -> Bool)
          , predicate (undefined :: Proxy "<")  ((<)  :: Int -> Int -> Bool)
          ]

and also activate the `DataKinds` extension.

And QuickSpec prints:

     11. x < y => insert x (y : xs) = x : (y : xs)
     12. x < y => insert y (x : xs) = x : insert y xs
     13. x <= y => insert x (y : xs) = x : (y : xs)

**Comment by MaximilianAlgehed** [comment]
Yeah, sorry about the `undefined :: Proxy ...` stuff, I haven't gotten around to hiding that yet...

**Comment by MaximilianAlgehed** [comment]
Hrm, this is a year old and QuickSpec has changed a bit since, so I hope you don't mind me closing this @rudymatela ;)

**Comment by rudymatela** [comment]
I certainly don't mind.  :-)
