### ISSUE TITLE
There is no function that returns [Equation]

### ISSUE THREAD

**Issue by NorfairKing** [nick8325/quickspec#17]
Something like `quickSpecOnSig :: Signature a => a -> IO [Equation]` or even `quickSpecOnSig :: Signature a => a -> Pipes.Producer [Equation]` would be nice.

**Comment by nick8325** [comment]
You can get the discovered laws out via the `background` field of the returned signature. It's a list of `Prop`s where each `Prop` should have the form `[] :=>: t :=: u`.

Having said that, the whole API is a huge mess and really needs reworking from the ground up.

**Comment by NorfairKing** [comment]
I was just made aware of the fact that the hackage version of quickspec is really old.
Are you planning on submitting the new releases?

**Comment by NorfairKing** [comment]
Hi @nick8325, What you suggested doesn't really work because the contents of that 'background' field ention functions as 'f12' instead of an actual name.
It would be good enough for me if the properties could be returned as a list of strings.
There isn't really a good way to capture the output since you are printing them to standard output.

**Comment by NorfairKing** [comment]
Actually, from looking at the code, I think I can make a function that shows the properties that are in the `background` field.

**Comment by nick8325** [comment]
Right, the `Show` instance is rather low-level. There is also a `Pretty` instance which should do what you want. In particular, `prettyShow` from [`Text.PrettyPrint.HughesPJClass`](https://hackage.haskell.org/package/prettyclass-1.0.0.0/docs/Text-PrettyPrint-HughesPJClass.html) ought to print everything properly.

**Comment by NorfairKing** [comment]
I managed to do what I wanted thanks to your help here,
With this code:

``` Haskell
\sig ->
    map Text.PrettyPrint.HughesPJClass.prettyShow
        (map
            (QuickSpec.Signature.prettyRename sig)
            (QuickSpec.Signature.background sig))
```
