### ISSUE TITLE
A way to silence quickspec

### ISSUE THREAD

**Issue by NorfairKing** [nick8325/quickspec#22]
My current use-case involves running quickspec programatically, and a lot of times.
As a result, I am battered my megabytes of output, including a bunch of unprintable characters due to (`putTemp`).
Is there no way to silence quickspec, so I can run `quickSpec` without producing any output?

**Comment by nick8325** [comment]
It doesn't look like there is, patches welcome though. You would want to add a flag to the signature, and then in `Eval.hs` take the call to `withStdioTerminal` and change it to `withNullTerminal` when output should be disabled.

**Comment by NorfairKing** [comment]
@nick8325 That is a remarkable practical solution. I'll have a go at it!
