### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by MaximilianAlgehed** [nick8325/quickspec#34]
We need some form of test suite to make sure we catch silly bugs.

* One thing to do would be to add regression tests by making sure the output of QuickSpec doesn't change across commits unless stated otherwise

**Comment by rudymatela** [comment]
Hey @MaximilianAlgehed,

You could do the same as Speculate:

* there is a set of examples of use of Speculate (e.g.: [plus-abs](https://github.com/rudymatela/speculate/blob/master/eg/plus-abs.hs));
* for each of those examples, a [reference output] is recorded by running [`make update-test-model`] -- I usually keep these tracked by git;
* whenever [`make test`] is run, the output of each example is tested against the recorded reference output;

[reference output]: https://github.com/rudymatela/speculate/blob/master/tests/model/plus-abs
[`make update-test-model`]: https://github.com/rudymatela/speculate/blob/master/tests/test-model
[`make test`]: https://github.com/rudymatela/speculate/blob/master/Makefile#L77-L78

I am using a makefile to manage this.  But I don't see a problem with doing this with cabal.

I do something similar on [LeanCheck], [FitSpec] and [Extrapolate].  @barrucadu does something similar on [CoCo]

[LeanCheck]: https://github.com/rudymatela/leancheck
[FitSpec]: https://github.com/rudymatela/fitspec
[Extrapolate]: https://github.com/rudymatela/extrapolate
[CoCo]: https://github.com/barrucadu/coco

This has the nice advantage of recording the effect of changes on the output when you are careful enough to update the reference outputs before commiting.  For example: https://github.com/rudymatela/speculate/commit/b1df5ef7bb964e249b38a182551456e41396df88

I may have mentioned this to you in person, so forgive me if I am repeating myself :-)  Just wanted to let you know as I think this may be helpful.

PS: the scripts I use to manage the reference outputs on Speculate is admittedly overengineered.  Maybe the scripts on LeanCheck and Extrapolate are a better reference if you ever want to implement something similar.

**Comment by nick8325** [comment]
Yeah, that sounds like a good way to do it!

**Comment by MaximilianAlgehed** [comment]
Hey @rudymatela,

That sounds like a nice way of doing it. Don't worry about repeating yourself,
I'm not the best at recalling past conversations anyway.

It would be nice to integrate this with some form of continous integration like
Travis or some other tool which runs builds and tests when commits are made.

**Comment by rudymatela** [comment]
> It would be nice to integrate this with some form of continous integration like
> Travis or some other tool which runs builds and tests when commits are made.

[Speculate](https://travis-ci.org/rudymatela/speculate) and [Extrapolate are under continuous integration on Travis](https://travis-ci.org/rudymatela/extrapolate).  Tests comparing output with a reference are active there.  So whenever output and reference do not match, [travis reports it](https://travis-ci.org/rudymatela/extrapolate/jobs/263450534).

For a near minimal example of using Travis+Haskell, you can check [hello-haskell](https://github.com/rudymatela/hello-haskell).

**Comment by MaximilianAlgehed** [comment]
@nick8325 Implemented something like this which can be found here:https://travis-ci.org/nick8325/quickspec
