### ISSUE TITLE
Feature request: an option to only search linear laws

### ISSUE THREAD

**Issue by isovector** [nick8325/quickspec#47]
Given a monomorphic type with lots of inductive constructors, quickspec finds _lots_ of laws. This is great sometimes, but many of the laws get in the way of "what's really going on" when instantiated non-linearly.

For example, given my signature

```text
andThen :: Workflow -> Workflow -> Workflow                                                                                                         
   both :: Workflow -> Workflow -> Workflow                                                                                                         
eitherW :: Workflow -> Workflow -> Workflow                                                                                                         
   gate :: EventFilter -> Workflow -> Workflow                                                                                                      
 reward :: Reward -> Workflow -> Workflow                                                                                                           
    win :: Workflow                                                                                                                                 
   lose :: Workflow
```

with term size 7, QS generates over 100 laws! However, many of these are of of a nonlinear form, eg:

`subgame w w2 (andThen w w3) = subgame w w2 w`

which is indeed true, but isn't a deep theorem (this one is equivalent to the law `ifThenElse a b a = ifThenElse a b False`). 

Having an optional `withLinearity :: Linearity -> Sig` signature constructor, that when set, prevents QuickSpec from instantiating terms that use the same variable twice would go a long way to pruning out theorems like these.

**Comment by nick8325** [comment]
I followed your suggestion of unifying this with the (previously-undocumented) `SingleUse` feature. So there is now a new API:

```
-- | Constrain how variables of a particular type may occur in a term.
-- The default value is @'UpTo' 4@.
variableUse :: forall proxy a. Typeable a => VariableUse -> proxy a -> Sig

-- | Constrains how variables of a particular type may occur in a term.
data VariableUse =
    UpTo Int -- ^ @UpTo n@: terms may contain up to @n@ distinct variables of this type
             -- (in some cases, laws with more variables may still be found)
  | Linear   -- ^ Each variable in the term must be distinct
```

You can say `variableUse Linear (Proxy :: Proxy Workflow)` to get the behaviour that you want.

**Comment by isovector** [comment]
Fantastic, thank you so much! Would you mind cutting a new release with this feature?

**Comment by nick8325** [comment]
It looks like my commit broke QuickSpec! Working on fixing it...

**Comment by nick8325** [comment]
OK, all fixed! I'll put out a new release ASAP (probably in a day or two).

**Comment by nick8325** [comment]
Done!

**Comment by isovector** [comment]
Looks like there's a [documentation build failure on hackage](https://hackage.haskell.org/package/quickspec-2.1.3/reports/3). [`uniform` was added in `random-1.2.0`](https://hackage.haskell.org/package/random-1.2.0/docs/System-Random.html#v:uniform) and breaks your module against the latest version of `random`.

**Comment by nick8325** [comment]
Oops! Should be fixed now!
